version: 2
jobs:
  build:
    working_directory: ~/my-app
    docker:
      - image: ruby:2.4.0
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run:
          name: Run Test
          command: bundle exec rspec
  deploy:
    working_directory: ~/my-app
    docker:
    - image: ruby:2.4.0
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rake deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop